# C-001 bootstrap: derive next actor/action from state.json + applicable review.
# Default is fail-closed and read-only. -Repair regenerates gitignored handoff.md.
# Does not merge. Does not push main. Does not implement.
param(
    [switch]$Repair
)

Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'

. (Join-Path $PSScriptRoot 'lib.ps1')
Assert-MergeForbidden

$root = Get-RepoRoot
$state = Get-StateObject -RepoRoot $root
$facts = Get-DerivedHandoffFacts -State $state -RepoRoot $root

Write-Host '=== bootstrap (C-001 derived from state.json + applicable review) ==='
Write-Host "task_id=$($facts.TaskId)"
Write-Host "status=$($facts.Status)"
Write-Host "plan_approved=$($facts.PlanApproved)"
Write-Host "review_round=$($facts.ReviewRound)"
Write-Host "next_actor=$($facts.NextActor)"
Write-Host "next_action=$($facts.NextAction)"
Write-Host "decision=$($facts.Decision)"
Write-Host "required_fixes_file=$($facts.RequiredFixesFile)"
Write-Host "report_file=$($facts.ReportFile)"
Write-Host "task_file=$($facts.TaskFile)"
Write-Host "human_instruction=$($facts.HumanInstruction)"
Write-Host 'reads:'
foreach ($r in $facts.Reads) { Write-Host "  - $r" }
Write-Host 'Human is spawn-only (C-003). Do not paste transcripts or rewrite B-nnn.'
Write-Host 'Do not gh pr merge. Do not spawn Review via SDK/subagent (D-003/D-004).'

$overlay = Read-HandoffOverlay -RepoRoot $root
if ($Repair) {
    $path = Write-DerivedHandoff -State $state -RepoRoot $root -Notes 'Regenerated by bootstrap.ps1 -Repair from authoritative state/review (C-001). Overlay is not SoT.'
    Write-Host "Repaired handoff: $path"
    exit 0
}

try {
    Assert-HandoffMatchesDerived -State $state -RepoRoot $root -Overlay $overlay | Out-Null
    Write-Host 'handoff matches derived facts (C-001).'
}
catch {
    Write-Host $_.Exception.Message
    Write-Host 'Fail closed. Re-run: pwsh -File scripts/workflow/bootstrap.ps1 -Repair'
    throw
}
